name = "DividedRectangles"
uuid = "8f25b07e-6077-4668-9c5e-9c6bcc4ef962"
authors = ["Integra-Spec-A <Anshrin@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1.10"

[extras]
Test = "b77e0a4c-74ae-5c0d-959a-9c0b98cddf26"

[targets]
test = ["Test"]
