name: CI

on:
  push:
    branches: [ "add-tests-only" ]
  pull_request:
    branches: [ "add-tests-only" ]
  workflow_dispatch:

jobs:
  build:
    # Use a matrix to run on multiple OS versions
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      # This will run on all specified operating systems
      - name: Run a one-line script
        run: echo Hello, world! Running on ${{ matrix.os }}

      # Run multiple commands as part of the CI process
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project on ${{ matrix.os }}

      # Set up Julia and run tests with coverage on all specified operating systems
      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.10'

      - name: Install dependencies
        run: julia -e 'using Pkg; Pkg.instantiate()'

      - name: Run tests with coverage
        run: julia --project=. -e 'using Pkg; Pkg.test(coverage=true)'

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
