name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Julia
      uses: julia-actions/setup-julia@v1
      with:
        version: 1.10.5

    - name: Install dependencies
      run: julia --project=. -e 'using Pkg; Pkg.instantiate()'

    - name: Run tests
      run: julia --project=. -e 'using Test; include("test/runtests.jl")'

    - name: Upload coverage to Codecov
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        julia --project=. -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
