name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Julia
      uses: julia-actions/setup-julia@v1
      with:
        version: '1.10' # Specify the Julia version

    - name: Install dependencies
      run: julia --project=. -e 'using Pkg; Pkg.instantiate()'

    - name: Run tests
      run: julia --project=. -e 'using Pkg; Pkg.test()'

    - name: Upload coverage to Codecov
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }} # Ensure this is set in your repository secrets
      run: |
        julia --project=. -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
