name: CI

on:
  push:
    branches: [ "add-tests-only" ]
  pull_request:
    branches: [ "add-tests-only" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: "1.6"

      - name: Install Dependencies
        run: julia -e 'using Pkg; Pkg.instantiate()'

      - name: Run Tests
        run: julia -e 'using Pkg; Pkg.test(coverage=true)'

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
