name: CI

on:
  push:
    branches: [ "add-tests-only" ]
  pull_request:
    branches: [ "add-tests-only" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.6'

      - name: Install dependencies
        run: julia -e 'using Pkg; Pkg.instantiate()'

      - name: Run tests with coverage
        run: julia --project=. --code-coverage=all test/runtests.jl

      - name: Upload coverage to Coveralls  # Or Codecov
        run: julia -e 'using Coverage; Coveralls.submit(Coveralls.process_folder())'
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
