name: CI

on:
  push:
    branches: ["add-tests-only"]
  pull_request:
    branches: ["add-tests-only"]
  workflow_dispatch:

jobs:
  build:
    # Use a matrix to run on multiple OS versions
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      # Setup Julia environment
      - name: Setup Julia
        uses: julia-actions/setup-julia@v2

      # Run the Julia script
      - name: Run tests
        run: |
          julia --project=. -e 'using Pkg; Pkg.instantiate()'
          julia --project=. -e 'using Pkg; Pkg.test()'

      # Upload code coverage to Codecov
      - name: Upload coverage to Codecov
        run: |
          julia --project=. -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'

      # Runs a one-line script to confirm job is running on all OSes
      - name: Confirm OS
        run: echo "Running on ${{ matrix.os }}"

      # Optional: Add detailed logging
      - name: Log system information
        run: |
          uname -a
          julia --version
