name: CI

on:
  push:
    branches: [ "add-tests-only" ]
  pull_request:
    branches: [ "add-tests-only" ]
  workflow_dispatch:

jobs:
  build:
    # Use a matrix to run on multiple OS versions
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.6'  # specify the Julia version you want to use

      - name: Install dependencies
        run: julia --project -e 'using Pkg; Pkg.instantiate()'

      - name: Run tests with coverage
        run: julia --project -e 'using Pkg; Pkg.test(coverage=true)'

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/*.json
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
