name: Julia CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Julia
      uses: julia-actions/setup-julia@v1
      with:
        version: '1.7'

    - name: Install Dependencies
      run: |
        julia -e 'using Pkg; Pkg.instantiate()'

    - name: Run Tests
      run: |
        julia -e 'using Pkg; Pkg.test()'

    - name: Lint Code
      run: |
        julia -e 'using Pkg; Pkg.add("JuliaFormatter"); using JuliaFormatter; format(".")'

