name: Documentation

on:
  push:
    branches:
      - main  # Adjust if you're using a different default branch
  pull_request:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.8'  # Adjust the Julia version as needed

      - name: Install dependencies
        run: julia --project=docs -e 'using Pkg; Pkg.instantiate()'

      - name: Build documentation
        run: julia --project=docs docs/make.jl

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build
