name: Documentation

on:
  push:
    branches:
      - main
    tags: [v*]
  pull_request:
    branches:
      - main

jobs:
  build:
    permissions:
      contents: write
      pages: write
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v4

      # Step 2: Set up Julia
      - name: Set up Julia
        uses: julia-actions/setup-julia@v1.5
        with:
          version: '1.6'  # Adjust this to your preferred Julia version

      # Step 3: Install dependencies for the documentation
      - name: Install dependencies
        run: julia --project=docs -e 'using Pkg; Pkg.instantiate();'

      # Step 4: Build the documentation
      - name: Build documentation
        run: julia --project=docs docs/make.jl

      # Step 5: Deploy documentation to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build  # The directory where the generated docs are located
